apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.project.openshift.io
spec:
  conversion:
    strategy: None
  group: project.openshift.io
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: "Project holds cluster-wide information about Project.  The canonical
          name is `cluster` \n Compatibility level 1: Stable within a major release
          for a minimum of 12 months or 3 minor releases (whichever is longer)."
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: spec holds user settable values for configuration
            properties:
              finalizers:
                description: projectRequestMessage is the string presented to a user
                  if they are unable to request a project via the projectrequest api
                  endpoint
                type: array
                items:
                  type: string
                  description: finalizers
            type: object
          status:
            description: status holds observed values from the cluster. They may not
              be overridden.
            type: object
            properties:
              phase:
                description: the phase
                type: string
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}



